/* ============================================================
 *
 * This file is a part of digiKam project
 * https://www.digikam.org
 *
 * Description : Photos mode - Qt Quick image providers backed by
 *               digiKam's thumbnail database and preview loaders.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * ============================================================ */

#pragma once

// Qt includes

#include <QCache>
#include <QElapsedTimer>
#include <QHash>
#include <QImage>
#include <QList>
#include <QMutex>
#include <QObject>
#include <QPointer>
#include <QSet>
#include <QStringList>
#include <QQuickAsyncImageProvider>
#include <QString>
#include <QThreadPool>

class QTimer;

namespace Digikam
{

class LoadingDescription;
class ThumbnailIdentifier;
class ThumbnailLoadThread;

/**
 * Lives in the GUI thread. Owns dedicated digiKam thumbnail loaders
 * (reading thumbnails-digikam.db, generating missing thumbnails exactly like
 * the classic views do) and an in-memory cache of decoded thumbnails.
 *
 * Sizes: thumbnails are served in a few fixed sizes (see sizes()). The grid
 * picks the size matching its tile size and scales it on the GPU, so zooming
 * within one size never reloads, and dense zoom levels use small textures.
 * A smaller size is scaled from a larger one already in memory when possible.
 *
 * Speed for libraries seen for the first time:
 *  - one loader per core work in parallel (a file always goes to the same one);
 *  - requests for tiles which scrolled away are cancelled, so the queue holds
 *    what is on screen (newest request first);
 *  - missing thumbnails of the whole library are pre-generated by several
 *    lowest-priority loaders, in small batches, and only while no visible
 *    thumbnail is waiting: digiKam's loaders share one thread pool, and long
 *    pre-generation queues would otherwise hold its threads.
 */
class PhotosThumbnailBroker : public QObject
{
    Q_OBJECT

public:

    explicit PhotosThumbnailBroker(QObject* const parent = nullptr);
    ~PhotosThumbnailBroker() override;

    /// Thumbnail sizes served, ascending (long side, in device pixels).
    QList<int> sizes() const;

    /// Thread-safe cache lookup.
    QImage cached(const QString& filePath, int size);

    /// Must be called in the GUI thread (use a queued invocation).
    void request(const QString& filePath, qlonglong imageId, int size);

    /// Must be called in the GUI thread: the requester does not need it any more.
    void cancel(const QString& filePath, int size);

    /// Background generation of missing thumbnails (GUI thread).
    void pregenerate(const QList<ThumbnailIdentifier>& identifiers);

    int loaderCount()       const;
    int pregeneratorCount() const;

Q_SIGNALS:

    void signalThumbnailReady(const QString& filePath, int size, const QImage& image);

    /// The file changed on disk: its thumbnail must be requested again.
    void signalThumbnailChanged(const QString& filePath);

    /// Background generation: number of photos handled so far, and total (0 when idle).
    void signalPregenerationProgress(int done, int total);

private Q_SLOTS:

    void slotImageLoaded(const LoadingDescription& description, const QImage& image);
    void slotFileChanged(const QString& filePath);
    void slotPregenerationTick();
    void slotCheckMemory();

private:

    static QString       cacheKey(const QString& filePath, int size);
    static qint64        cacheBudgetKiB();
    void                 store(const QString& filePath, int size, const QImage& image);
    void                 deliver(const QString& filePath, int size, const QImage& image);
    ThumbnailLoadThread* loaderFor(const QString& filePath) const;
    void                 pausePregeneration();
    bool                 scaleFromLarger(const QString& filePath, int size);

private:

    QList<ThumbnailLoadThread*>                       m_loaders;
    QList<ThumbnailLoadThread*>                       m_pregenerators;
    QHash<ThumbnailLoadThread*, QList<ThumbnailIdentifier> > m_pregenInFlight;
    QList<ThumbnailIdentifier>                        m_pregenQueue;
    int                                               m_pregenCursor = 0;
    int                                               m_pregenTotal  = 0;
    QTimer*                                           m_pregenTimer  = nullptr;
    QElapsedTimer                                     m_lastRequest;

    QHash<QString, int>                               m_pending;    ///< key -> waiting requests, GUI thread only.
    QMutex                                            m_mutex;
    QCache<QString, QImage>                           m_cache;
    qint64                                            m_cacheBudget  = 0;      ///< KiB, before memory pressure.
    QTimer*                                           m_memoryTimer  = nullptr;
    QThreadPool                                       m_scalePool;
    QList<int>                                        m_sizes;
};

// -------------------------------------------------------------------------------

class PhotosThumbnailProvider : public QQuickAsyncImageProvider
{
public:

    explicit PhotosThumbnailProvider(PhotosThumbnailBroker* const broker);

    /// id format: "<imageId>/<version>/<size>/<base64url file path>"
    QQuickImageResponse* requestImageResponse(const QString& id, const QSize& requestedSize) override;

private:

    PhotosThumbnailBroker* m_broker = nullptr;
};

// -------------------------------------------------------------------------------

/**
 * Screen sized previews for the full screen viewer, decoded by a small pool
 * of threads and kept in a memory budgeted cache (see
 * PhotosCachePolicy::previewBudgetKiB(); it shrinks under memory pressure).
 *
 *  - The photo on screen is requested through the "dkpreview" image provider
 *    and always comes first; one thread is kept for it.
 *  - The neighbours given to prefetch() (next ones first) are decoded ahead
 *    with the remaining threads, so going to them shows them instantly.
 *  - A decode is never done twice: a request for a photo being prefetched
 *    waits for that job. Prefetches no longer wanted are dropped.
 *
 * Thread safe: the image provider calls it from Qt Quick's loader thread.
 */
class PhotosPreviewLoader : public QObject
{
    Q_OBJECT

public:

    explicit PhotosPreviewLoader(QObject* const parent = nullptr);
    ~PhotosPreviewLoader() override;

    /**
     * Asks for the preview of filePath with a long side of at least size
     * (0: full resolution, not cached). The receiver's Q_INVOKABLE
     * setPreview(QImage) is called (queued) with the result.
     */
    void request(const QString& filePath, int size, QObject* const receiver);

    /// The receiver does not want the result any more.
    void cancel(const QString& filePath, int size, QObject* const receiver);

    /// Decodes these previews ahead, most important first. Replaces the previous list.
    void prefetch(const QStringList& filePaths, int size);

    int threadCount() const;

private Q_SLOTS:

    void slotCheckMemory();

private:

    struct Job
    {
        QString                  filePath;
        int                      size     = 0;
        int                      priority = 0;      ///< 0: on screen, then prefetch order.
        bool                     running  = false;
        QList<QPointer<QObject>> receivers;
    };

    static QString key(const QString& filePath, int size);
    void           dispatchLocked();
    void           jobDone(const QString& jobKey, const QImage& image, qint64 elapsedMs);

private:

    mutable QMutex          m_mutex;
    QHash<QString, Job>     m_jobs;
    QSet<QString>           m_prefetchKeys;
    QCache<QString, QImage> m_cache;
    qint64                  m_budget      = 0;        ///< KiB, before memory pressure.
    int                     m_running     = 0;
    int                     m_threads     = 2;
    bool                    m_trace       = false;
    QThreadPool             m_pool;
    QTimer*                 m_memoryTimer = nullptr;
};

// -------------------------------------------------------------------------------

class PhotosPreviewProvider : public QQuickAsyncImageProvider
{
public:

    explicit PhotosPreviewProvider(PhotosPreviewLoader* const loader);

    /**
     * id format: "<size>/<base64url file path>".
     * size > 0 loads a fast preview at least that large (embedded previews
     * when big enough), size == 0 loads the full resolution image.
     */
    QQuickImageResponse* requestImageResponse(const QString& id, const QSize& requestedSize) override;

private:

    QPointer<PhotosPreviewLoader> m_loader;
};

} // namespace Digikam
